---
type: cloudgenix template
version: 1.0
# Created at 2021-04-12T15:23:11.465335Z
# by system_2750@soumyars.com
sites v4.5:
  Test_buzz_app:
    address:
    admin_state: disabled
    description:
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 0.0
      longitude: 0.0
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
