---
type: cloudgenix template
version: 1.0
# Created at 2021-02-18T08:41:38.284170Z
# by system_100@cyberdyne.com
sites v4.5:
  Test-HUB:
    address:
    admin_state: active
    description:
    element_cluster_role: HUB
    elements v2.3: {}
    extended_tags:
    hubclusters v2.0:
      default-100-16136371342210213:
        admin_up: true
        load_alarm_threshold: 90
        subscription_factor: 0.5
    location:
      description:
      latitude: 0.0
      longitude: 0.0
    nat_policysetstack_id:
    network_policysetstack_id:
    policy_set_id:
    priority_policysetstack_id:
    security_policyset_id:
    service_binding:
    tags:
