---
type: cloudgenix template
version: 1.0
# Created at 2021-03-12T07:20:16.452629Z
# by system_1062@soumya_elcap.com
sites v4.5:
  BRANCH-BLR:
    address:
      city: Bengaluru
      country: India
      post_code:
      state: Karnataka
      street: Vidhansaudha
      street2:
    admin_state: disabled
    description:
    element_cluster_role: SPOKE
    elements v2.3:
      SPOKE-3K:
        admin_action:
        admin_renew_state:
        allowed_roles:
        - HUB
        - SPOKE
        cluster_insertion_mode:
        cluster_member_id:
        connected: false
        deployment_op:
        description:
        element_security_zones v2.0: []
        interfaces v4.9:
          '1':
            admin_up: false
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipv4_config:
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id:
            network_context_id:
            parent:
            pppoe_config:
            scope: local
            service_link_config:
            site_wan_interface_ids:
            sub_interface:
            tags:
            type: port
            used_for: none
          '2':
            admin_up: false
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipv4_config:
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id:
            network_context_id:
            parent:
            pppoe_config:
            scope: local
            service_link_config:
            site_wan_interface_ids:
            sub_interface:
            tags:
            type: port
            used_for: none
          '3':
            admin_up: false
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipv4_config:
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id:
            network_context_id:
            parent:
            pppoe_config:
            scope: local
            service_link_config:
            site_wan_interface_ids:
            sub_interface:
            tags:
            type: port
            used_for: none
          '4':
            admin_up: false
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipv4_config:
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id:
            network_context_id:
            parent:
            pppoe_config:
            scope: local
            service_link_config:
            site_wan_interface_ids:
            sub_interface:
            tags:
            type: port
            used_for: none
          '5':
            admin_up: false
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipv4_config:
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id:
            network_context_id:
            parent:
            pppoe_config:
            scope: local
            service_link_config:
            site_wan_interface_ids:
            sub_interface:
            tags:
            type: port
            used_for: none
          '6':
            admin_up: false
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipv4_config:
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id:
            network_context_id:
            parent:
            pppoe_config:
            scope: local
            service_link_config:
            site_wan_interface_ids:
            sub_interface:
            tags:
            type: port
            used_for: none
          '7':
            admin_up: false
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipv4_config:
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id:
            network_context_id:
            parent:
            pppoe_config:
            scope: local
            service_link_config:
            site_wan_interface_ids:
            sub_interface:
            tags:
            type: port
            used_for: none
          '8':
            admin_up: false
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipv4_config:
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id:
            network_context_id:
            parent:
            pppoe_config:
            scope: local
            service_link_config:
            site_wan_interface_ids:
            sub_interface:
            tags:
            type: port
            used_for: none
          controller 1:
            admin_up: true
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipv4_config:
              dhcp_config:
              dns_v4_config:
              routes:
              static_config:
              type: dhcp
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id:
            network_context_id:
            parent:
            pppoe_config:
            scope: local
            service_link_config:
            site_wan_interface_ids:
            sub_interface:
            tags:
            type: port
            used_for: none
        l3_direct_private_wan_forwarding: false
        l3_lan_forwarding: false
        model_name: ion 3102v
        nat_policysetstack_id:
        network_policysetstack_id:
        ntp v2.0:
        - description: Default NTP template created by super user.
          name: default
          ntp_servers:
          - host: 0.cloudgenix.pool.ntp.org
            max_poll: 10
            min_poll: 9
            version: 4
          - host: 1.cloudgenix.pool.ntp.org
            max_poll: 10
            min_poll: 9
            version: 4
          - host: 2.cloudgenix.pool.ntp.org
            max_poll: 10
            min_poll: 9
            version: 4
          - host: 3.cloudgenix.pool.ntp.org
            max_poll: 10
            min_poll: 9
            version: 4
          - host: time.nist.gov
            max_poll: 15
            min_poll: 13
            version: 4
          source_interface_ids:
          tags:
        priority_policysetstack_id:
        role: SPOKE
        routing:
          bgp:
            global_config v2.2:
              admin_distance: 20
              adv_interval: 1
              graceful_restart: false
              hold_time: 90
              keepalive_time: 30
              local_as_num:
              maximum_paths: 1
              md5_secret:
              multi_hop_limit: 1
              peer_auth_type: none
              peer_retry_time: 120
              prefix_adv_type:
              prefix_adv_type_to_lan: default
              prefixes_to_adv_to_wan:
              router_id:
              stalepath_time: 120
          static v2.0: []
        serial_number: 470c1542-7c98-5fcc-1b10-7bea821a1ec8
        software_version: 5.4.3-b9
        spoke_ha_config:
        state: bound
        tags:
        tenant_id: '1062'
        toolkit v2.2:
          account_disable_interval: 5
          inactive_interval: 15
          otpkey_version: 1
          retry_login_count: 5
          ssh_enabled: true
          ssh_outbound_enabled: false
        vpn_to_vpn_forwarding: false
    extended_tags:
    location:
      description:
      latitude: 12.96991
      longitude: 77.59796
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: Default Path Simple Stack (Simple)
    policy_set_id:
    priority_policysetstack_id: Default QoS Simple Stack (Simple)
    security_policyset_id:
    service_binding: Preset Domain
    tags:
