sites v4.5:
  AHMADABAD_SITE:
    address:
      city: AHMADABAD
      country: India
      post_code:
      state:
      street:
      street2:
    admin_state: disabled
    description: this Spoke for site1:2 AHMADABAD
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    hubclusters v2.0:
      default-2750-16016082061230098:
        admin_up: true
        load_alarm_threshold: 90
        subscription_factor: 0.5
    location:
      description:
      latitude: '23.0301'
      longitude: '72.5800'
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
    waninterfaces v2.5:
      Circuit to At&T:
        bfd_mode: aggressive
        bw_config_mode: manual
        bwc_enabled: true
        cost: 128
        description:
        label_id: MPLS
        link_bw_down: 30.0
        link_bw_up: 10.0
        lqm_config:
        lqm_enabled: true
        network_id: At&T
        network_type: privatewan
        tags:
        type: privatewan
        vpnlink_configuration:
      Circuit to BSNL:
        bfd_mode: aggressive
        bw_config_mode: manual
        bwc_enabled: true
        cost: 128
        description:
        label_id: Internet DSL
        link_bw_down: 30.0
        link_bw_up: 10.0
        lqm_config:
        lqm_enabled: true
        network_id: BSNL
        network_type: publicwan
        tags:
        type: publicwan
        vpnlink_configuration:
type: cloudgenix template
version: 1.0
