---
type: cloudgenix template
version: 1.0
# Created at 2021-03-03T05:57:08.204900Z
# by system_100@cyberdyne.com
sites v4.5:
  test_etna:
    address:
    admin_state: active
    description:
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description: none
      latitude: 39.85599136352539
      longitude: -82.88740539550781
    nat_policysetstack_id:
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
