---
type: cloudgenix template
version: 1.0
# Created at 2021-04-21T05:47:40.125997Z
# by system_1062@soumya_elcap.com
sites v4.5:
  test:
    address:
      city: Hyderabad
      country: India
      post_code:
      state: Telangana
      street: chickpet
      street2:
    admin_state: active
    description:
    dhcpservers v2.1:
    - broadcast_address: 172.16.60.255
      custom_options:
      default_lease_time: 43200
      description:
      disabled: false
      dns_servers:
      - 10.8.8.21
      - 75.75.75.75
      - 8.8.8.8
      domain_name:
      gateway: 172.16.60.1
      ip_ranges:
      - end_ip: 172.16.60.50
        start_ip: 172.16.60.2
      max_lease_time: 86400
      network_context_id:
      static_mappings:
      subnet: 172.16.60.0/24
      tags:
    element_cluster_role: SPOKE
    elements v2.3:
      test_elem:
        admin_action:
        admin_renew_state:
        allowed_roles:
        - HUB
        - SPOKE
        cluster_insertion_mode:
        cluster_member_id:
        connected: true
        deployment_op:
        description:
        element_security_zones v2.0: []
        interfaces v4.9:
          '1':
            admin_up: false
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipv4_config:
              dhcp_config:
              dns_v4_config:
              routes:
              static_config:
              type: dhcp
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id: internet
            network_context_id:
            parent:
            pppoe_config:
            scope: local
            service_link_config:
            site_wan_interface_ids:
            sub_interface:
            tags:
            type: port
            used_for: public
          '2':
            admin_up: true
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipv4_config:
              dhcp_config:
              dns_v4_config:
                name_servers:
                - 8.8.8.8
              routes:
              static_config:
                address: 172.16.60.1/24
              type: static
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id:
            network_context_id:
            parent:
            pppoe_config:
            scope: global
            service_link_config:
            site_wan_interface_ids:
            sub_interface:
            tags:
            type: port
            used_for: lan
          '3':
            admin_up: true
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipv4_config:
              dhcp_config:
              dns_v4_config:
              routes:
              static_config:
              type: dhcp
            mac_address:
            mtu: 1500
            nat_address: 106.51.85.41
            nat_pools:
            nat_port: 4500
            nat_zone_id: internet
            network_context_id:
            parent:
            pppoe_config:
            scope: local
            service_link_config:
            site_wan_interface_ids:
            - Circuit to Airtel
            sub_interface:
            tags:
            - azure_enabled_uksouth
            type: port
            used_for: public
          '4':
            admin_up: false
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipv4_config:
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id:
            network_context_id:
            parent:
            pppoe_config:
            scope: local
            service_link_config:
            site_wan_interface_ids:
            sub_interface:
            tags:
            type: port
            used_for: none
          '5':
            admin_up: false
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipv4_config:
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id:
            network_context_id:
            parent:
            pppoe_config:
            scope: local
            service_link_config:
            site_wan_interface_ids:
            sub_interface:
            tags:
            type: port
            used_for: none
          '6':
            admin_up: false
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipv4_config:
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id:
            network_context_id:
            parent:
            pppoe_config:
            scope: local
            service_link_config:
            site_wan_interface_ids:
            sub_interface:
            tags:
            type: port
            used_for: none
          '7':
            admin_up: false
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipv4_config:
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id:
            network_context_id:
            parent:
            pppoe_config:
            scope: local
            service_link_config:
            site_wan_interface_ids:
            sub_interface:
            tags:
            type: port
            used_for: none
          '8':
            admin_up: false
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipv4_config:
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id:
            network_context_id:
            parent:
            pppoe_config:
            scope: local
            service_link_config:
            site_wan_interface_ids:
            sub_interface:
            tags:
            type: port
            used_for: none
          controller 1:
            admin_up: true
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipv4_config:
              dhcp_config:
              dns_v4_config:
              routes:
              static_config:
              type: dhcp
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id:
            network_context_id:
            parent:
            pppoe_config:
            scope: local
            service_link_config:
            site_wan_interface_ids:
            sub_interface:
            tags:
            type: port
            used_for: none
          sl-zscaler-16154082797040027:
            admin_up: true
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: Created by ZScaler Integration App
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
            ipv4_config:
              dhcp_config:
              dns_v4_config:
              routes:
              static_config:
                address: 192.168.237.1/30
              type: static
            mac_address:
            mtu: 1400
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id:
            network_context_id:
            parent: '3'
            pppoe_config:
            scope: local
            service_link_config:
              gre_config:
              ipsec_config:
                authentication:
                  certificate:
                  ikev1_params:
                  local_ca_certificate:
                  local_id: custom
                  local_id_custom: 16186798759890045_1062@demo-cloudgenix.com
                  passphrase:
                  private_key:
                  remote_ca_certificate:
                  remote_id:
                  secret:
                  type: psk
                ipsec_profile_id: ZSCALER_IKEV2
              peer:
              service_endpoint_id: ZScaler
              type: ipsec
            site_wan_interface_ids:
            sub_interface:
            tags:
            - Zscaler-integrator-managed
            type: service_link
            used_for: none
        l3_direct_private_wan_forwarding: true
        l3_lan_forwarding: true
        model_name: ion 3102v
        nat_policysetstack_id:
        network_policysetstack_id:
        ntp v2.0:
        - description: Default NTP template created by super user.
          name: default
          ntp_servers:
          - host: 0.cloudgenix.pool.ntp.org
            max_poll: 10
            min_poll: 9
            version: 4
          - host: 1.cloudgenix.pool.ntp.org
            max_poll: 10
            min_poll: 9
            version: 4
          - host: 2.cloudgenix.pool.ntp.org
            max_poll: 10
            min_poll: 9
            version: 4
          - host: 3.cloudgenix.pool.ntp.org
            max_poll: 10
            min_poll: 9
            version: 4
          - host: time.nist.gov
            max_poll: 15
            min_poll: 13
            version: 4
          source_interface_ids:
          tags:
        priority_policysetstack_id:
        role: SPOKE
        routing:
          bgp:
            global_config v2.2:
              admin_distance: 20
              adv_interval: 1
              graceful_restart: false
              hold_time: 90
              keepalive_time: 30
              local_as_num: '64512'
              maximum_paths: 1
              md5_secret:
              multi_hop_limit: 1
              peer_auth_type: none
              peer_retry_time: 120
              prefix_adv_type: unaggregated
              prefix_adv_type_to_lan: default
              prefixes_to_adv_to_wan:
              router_id:
              stalepath_time: 120
          static v2.0: []
        serial_number: d3041542-065e-9cfb-0f45-881102b907a7
        software_version: 5.4.3-b9
        spoke_ha_config:
        state: bound
        tags:
        tenant_id: '1062'
        toolkit v2.2:
          account_disable_interval: 5
          inactive_interval: 15
          otpkey_version: 1
          retry_login_count: 5
          ssh_enabled: true
          ssh_outbound_enabled: false
        vpn_to_vpn_forwarding: false
    extended_tags:
    - key: AUTO-zscaler
      value: '{"customEndpointName":"","gatewayOptions":{"zappSslScanEnabled":false,"xffForwardEnabled":false,"sslScanEnabled":false,"authRequired":false,"ofwEnabled":false,"aupEnabled":false,"cautionEnabled":false},"subLocations":[{"name":"test","ipAddresses":["192.168.30.2"],"gatewayOptions":{"zappSslScanEnabled":false,"xffForwardEnabled":false,"sslScanEnabled":false,"authRequired":false,"ofwEnabled":false,"aupEnabled":false,"cautionEnabled":false}},{"name":"other","ipAddresses":[],"gatewayOptions":{"zappSslScanEnabled":false,"xffForwardEnabled":false,"sslScanEnabled":false,"authRequired":false,"ofwEnabled":false,"aupEnabled":false,"cautionEnabled":false}}]}'
      value_type: object
    lannetworks v3.1:
      default_test_157730149:
        description:
        ipv4_config:
          default_routers:
          dhcp_relay:
          dhcp_server:
          prefixes:
          - 172.16.60.0/24
        network_context_id:
        scope: global
        tags:
    location:
      description:
      latitude: 17.36667
      longitude: 78.46667
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: Default Path Simple Stack (Simple)
    policy_set_id:
    priority_policysetstack_id: Default QoS Simple Stack (Simple)
    security_policyset_id:
    service_binding: Preset Domain
    tags:
    - AUTO-zscaler
    waninterfaces v2.6:
      Circuit to Airtel:
        bfd_mode: aggressive
        bw_config_mode: manual
        bwc_enabled: true
        cost: 128
        description:
        label_id: Ethernet Internet
        link_bw_down: 30.0
        link_bw_up: 10.0
        lqm_config:
        lqm_enabled: true
        network_id: Airtel
        network_type: publicwan
        tags:
        type: publicwan
        use_for_application_reachability_probes:
        use_for_controller_connections:
        vpnlink_configuration:
