---
type: cloudgenix template
version: 1.0
# Created at 2021-04-12T13:01:35.771246Z
# by system_1081@shiva.com
sites v4.5:
  BRANCH-BLR:
    address:
      city: Bengaluru
      country: India
      post_code:
      state: Karnataka
      street: Vidhansaudha
      street2:
    admin_state: disabled
    description:
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 12.96991
      longitude: 77.59796
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: Default Path Simple Stack (Simple)
    policy_set_id:
    priority_policysetstack_id: Default QoS Simple Stack (Simple)
    security_policyset_id:
    service_binding: Preset Domain
    tags:
