---
type: cloudgenix template
version: 1.0
# Created at 2021-04-08T15:04:02.001954Z
# by system_1100@testaccount.com
sites v4.5:
  MUMBAI-NW-DEVICE-3:
    address:
      city: Mumbai
      country: India
      post_code:
      state: Maharashtra
      street:
      street2:
    admin_state: active
    description:
    element_cluster_role: SPOKE
    elements v2.3:
      Mumbai-NE-Device-3:
        admin_action:
        admin_renew_state:
        allowed_roles:
        - HUB
        - SPOKE
        cluster_insertion_mode:
        cluster_member_id:
        connected: true
        deployment_op:
        description:
        element_security_zones v2.0: []
        interfaces v4.9:
          '1':
            admin_up: true
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipv4_config:
              dhcp_config:
              dns_v4_config:
              routes:
              static_config:
              type: dhcp
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id: internet
            network_context_id:
            parent:
            pppoe_config:
            scope: global
            service_link_config:
            site_wan_interface_ids:
            sub_interface:
            tags:
            type: port
            used_for: public
          '2':
            admin_up: true
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipv4_config:
              dhcp_config:
              dns_v4_config:
              routes:
              static_config:
              type: dhcp
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id: internet
            network_context_id:
            parent:
            pppoe_config:
            scope: global
            service_link_config:
            site_wan_interface_ids:
            sub_interface:
            tags:
            type: port
            used_for: public
          '3':
            admin_up: true
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipv4_config:
              dhcp_config:
              dns_v4_config:
              routes:
              static_config:
              type: dhcp
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id: internet
            network_context_id:
            parent:
            pppoe_config:
            scope: global
            service_link_config:
            site_wan_interface_ids:
            sub_interface:
            tags:
            type: port
            used_for: public
          '4':
            admin_up: true
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipv4_config:
              dhcp_config:
              dns_v4_config:
              routes:
              static_config:
              type: dhcp
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id: internet
            network_context_id:
            parent:
            pppoe_config:
            scope: local
            service_link_config:
            site_wan_interface_ids:
            sub_interface:
            tags:
            type: port
            used_for: public
          '5':
            admin_up: true
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipv4_config:
              dhcp_config:
              dns_v4_config:
              routes:
              static_config:
              type: dhcp
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id: internet
            network_context_id:
            parent:
            pppoe_config:
            scope: global
            service_link_config:
            site_wan_interface_ids:
            sub_interface:
            tags:
            type: port
            used_for: public
          '6':
            admin_up: true
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipv4_config:
              dhcp_config:
              dns_v4_config:
              routes:
              static_config:
              type: dhcp
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id: internet
            network_context_id:
            parent:
            pppoe_config:
            scope: global
            service_link_config:
            site_wan_interface_ids:
            sub_interface:
            tags:
            type: port
            used_for: public
          '7':
            admin_up: true
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipv4_config:
              dhcp_config:
              dns_v4_config:
              routes:
              static_config:
              type: dhcp
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id: internet
            network_context_id:
            parent:
            pppoe_config:
            scope: global
            service_link_config:
            site_wan_interface_ids:
            sub_interface:
            tags:
            type: port
            used_for: public
          '8':
            admin_up: false
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipv4_config:
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id:
            network_context_id:
            parent:
            pppoe_config:
            scope: local
            service_link_config:
            site_wan_interface_ids:
            sub_interface:
            tags:
            type: port
            used_for: none
          controller 1:
            admin_up: true
            attached_lan_networks:
            bound_interfaces:
            bypass_pair:
            description: ''
            devicemgmt_policysetstack_id:
            dhcp_relay:
            directed_broadcast: false
            ethernet_port:
              full_duplex: false
              speed: 0
            ipv4_config:
              dhcp_config:
              dns_v4_config:
              routes:
              static_config:
              type: dhcp
            mac_address:
            mtu: 1500
            nat_address:
            nat_pools:
            nat_port: 0
            nat_zone_id:
            network_context_id:
            parent:
            pppoe_config:
            scope: local
            service_link_config:
            site_wan_interface_ids:
            sub_interface:
            tags:
            type: port
            used_for: none
        l3_direct_private_wan_forwarding: false
        l3_lan_forwarding: false
        model_name: ion 3102v
        nat_policysetstack_id:
        network_policysetstack_id:
        ntp v2.0:
        - description: Default NTP template created by super user.
          name: default
          ntp_servers:
          - host: 0.cloudgenix.pool.ntp.org
            max_poll: 10
            min_poll: 9
            version: 4
          - host: 1.cloudgenix.pool.ntp.org
            max_poll: 10
            min_poll: 9
            version: 4
          - host: 2.cloudgenix.pool.ntp.org
            max_poll: 10
            min_poll: 9
            version: 4
          - host: 3.cloudgenix.pool.ntp.org
            max_poll: 10
            min_poll: 9
            version: 4
          - host: time.nist.gov
            max_poll: 15
            min_poll: 13
            version: 4
          source_interface_ids:
          tags:
        priority_policysetstack_id:
        role: SPOKE
        routing:
          bgp:
            global_config v2.2:
              admin_distance: 20
              adv_interval: 1
              graceful_restart: false
              hold_time: 90
              keepalive_time: 30
              local_as_num:
              maximum_paths: 1
              md5_secret:
              multi_hop_limit: 1
              peer_auth_type: none
              peer_retry_time: 120
              prefix_adv_type:
              prefix_adv_type_to_lan: default
              prefixes_to_adv_to_wan:
              router_id:
              stalepath_time: 120
          static v2.0: []
        serial_number: dfa01542-c92e-ee08-2562-c066d104cf65
        software_version: 5.4.3-b9
        spoke_ha_config:
        state: bound
        tags:
        tenant_id: '1100'
        toolkit v2.2:
          account_disable_interval: 5
          inactive_interval: 15
          otpkey_version: 1
          retry_login_count: 5
          ssh_enabled: true
          ssh_outbound_enabled: false
        vpn_to_vpn_forwarding: false
    extended_tags:
    location:
      description:
      latitude: 18.96667
      longitude: 72.83333
    nat_policysetstack_id:
    network_policysetstack_id:
    policy_set_id: AppPolSet01
    priority_policysetstack_id:
    security_policyset_id:
    service_binding: Preset Domain
    tags:
    waninterfaces v2.6:
      Circuit to INTERNET1:
        bfd_mode: aggressive
        bw_config_mode: manual
        bwc_enabled: true
        cost: 128
        description:
        label_id: Ethernet Internet
        link_bw_down: 30.0
        link_bw_up: 10.0
        lqm_config:
        lqm_enabled: true
        network_id: INTERNET1
        network_type: publicwan
        tags:
        type: publicwan
        use_for_application_reachability_probes:
        use_for_controller_connections:
        vpnlink_configuration:
      Circuit to INTERNET2:
        bfd_mode: aggressive
        bw_config_mode: manual
        bwc_enabled: true
        cost: 128
        description:
        label_id: Internet Cable
        link_bw_down: 30.0
        link_bw_up: 10.0
        lqm_config:
        lqm_enabled: true
        network_id: INTERNET2
        network_type: publicwan
        tags:
        type: publicwan
        use_for_application_reachability_probes:
        use_for_controller_connections:
        vpnlink_configuration:
      Circuit to INTERNET3:
        bfd_mode: aggressive
        bw_config_mode: manual
        bwc_enabled: true
        cost: 128
        description:
        label_id: Internet DSL
        link_bw_down: 30.0
        link_bw_up: 10.0
        lqm_config:
        lqm_enabled: true
        network_id: INTERNET3
        network_type: publicwan
        tags:
        type: publicwan
        use_for_application_reachability_probes:
        use_for_controller_connections:
        vpnlink_configuration:
      Circuit to INTERNET4:
        bfd_mode: aggressive
        bw_config_mode: manual
        bwc_enabled: true
        cost: 128
        description:
        label_id: public-10
        link_bw_down: 30.0
        link_bw_up: 10.0
        lqm_config:
        lqm_enabled: true
        network_id: INTERNET4
        network_type: publicwan
        tags:
        type: publicwan
        use_for_application_reachability_probes:
        use_for_controller_connections:
        vpnlink_configuration:
      Circuit to INTERNET5:
        bfd_mode: aggressive
        bw_config_mode: manual
        bwc_enabled: true
        cost: 128
        description:
        label_id: public-11
        link_bw_down: 30.0
        link_bw_up: 10.0
        lqm_config:
        lqm_enabled: true
        network_id: INTERNET5
        network_type: publicwan
        tags:
        type: publicwan
        use_for_application_reachability_probes:
        use_for_controller_connections:
        vpnlink_configuration:
      Circuit to INTERNET6:
        bfd_mode: aggressive
        bw_config_mode: manual
        bwc_enabled: true
        cost: 128
        description:
        label_id: public-12
        link_bw_down: 30.0
        link_bw_up: 10.0
        lqm_config:
        lqm_enabled: true
        network_id: INTERNET6
        network_type: publicwan
        tags:
        type: publicwan
        use_for_application_reachability_probes:
        use_for_controller_connections:
        vpnlink_configuration:
      Circuit to INTERNET7:
        bfd_mode: aggressive
        bw_config_mode: manual
        bwc_enabled: true
        cost: 128
        description:
        label_id: public-13
        link_bw_down: 30.0
        link_bw_up: 10.0
        lqm_config:
        lqm_enabled: true
        network_id: INTERNET7
        network_type: publicwan
        tags:
        type: publicwan
        use_for_application_reachability_probes:
        use_for_controller_connections:
        vpnlink_configuration:
