---
type: cloudgenix template
version: 1.0
# Created at 2021-02-18T08:44:44.472949Z
# by system_100@cyberdyne.com
sites v4.5:
  BANGALORE_SITE_:
    address:
    admin_state: active
    description:
    element_cluster_role: SPOKE
    elements v2.3: {}
    extended_tags:
    location:
      description:
      latitude: 0.0
      longitude: 0.0
    nat_policysetstack_id: Default-NATPolicySetStack
    network_policysetstack_id: NetworkPolicySetStack
    policy_set_id:
    priority_policysetstack_id: PriorityPolicySetStack
    security_policyset_id:
    service_binding: Preset Domain
    tags:
